services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80" # Tráfego HTTP público
      - "443:443" # Tráfego HTTPS público
      - "${PORT_MACHINE_NGINX}:81" # Interface de administração do NPM
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - management-network

networks:
  management-network:
    external: true

volumes:
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local