services:
  backend:
    build: ./backend
    # image: ghcr.io/ifpebj-ti/polifarm-backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    # image: ghcr.io/ifpebj-ti/polifarm-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge