name: Pull requests CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
      name: Frontend CI
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
        
        - name: Install dependencies
          run: |
            cd frontend
            npm install
  
        - name: Run ESLint
          run: |
            cd frontend
            npm run lint
            
        - name: Run Build
          run: |
            cd frontend
            docker build -t ghcr.io/ifpebj-ti/polifarm-frontend:latest .

        - name: Docker Login
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_PACKAGES_TOKEN }}

        - name: Docker Login
          uses: docker/login-action@v3.4.0
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Scan Docker image (Docker Scout)
          run: |
            curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
            sh install-scout.sh
            docker scout quickview ghcr.io/ifpebj-ti/polifarm-frontend:latest
            docker scout cves ghcr.io/ifpebj-ti/polifarm-frontend:latest

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      
      - name: Install dependencies
        run: |
          cd backend
          dotnet restore

      - name: Run Build
        run: |
          cd backend
          dotnet build --configuration Release
          
      - name: Run Tests
        run: |
          cd backend
          echo "Ainda não tem testes"

      - name: Docker Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Scan Docker image (Docker Scout)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview ghcr.io/ifpebj-ti/polifarm-backend:latest
          docker scout cves ghcr.io/ifpebj-ti/polifarm-backend:latest
