name: Production CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
      name: Frontend CI/CD
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4

        - name: Docker Login
        - uses: docker/login-action@v3.4.0
          with:
            registry: ghcr.io
            username: ifpebj-ti
            password: ${{ secrets.GH_PACKAGES_TOKEN }}

        - name: Build and push Docker images
        - uses: docker/build-push-action@v6.16.0
          with:
            context: ./frontend/
            push: true
            tags: ghcr.io/ifpebj-ti/polifarm-frontend:latest

  backend:
      name: Backend CI/CD
      runs-on: ubuntu-latest
    
      steps:
        - uses: actions/checkout@v4
  
        - name: Docker Login
        - uses: docker/login-action@v3.4.0
          with:
            registry: ghcr.io
            username: ifpebj-ti
            password: ${{ secrets.GH_PACKAGES_TOKEN }}
  
        - name: Build and push Docker images
        - uses: docker/build-push-action@v6.16.0
          with:
            context: ./backend/
            push: true
            tags: ghcr.io/ifpebj-ti/polifarm-backend:latest
